project_id = "your-project-id"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[db]
enabled = true
port = 54322
shadow_port = 54325
major_version = 15

[edge_runtime]
enabled = true
port = 54323

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.refresh-subscription]
verify_jwt = true

[functions.stripe-portal]
verify_jwt = true

[functions.stripe-refund]
verify_jwt = true

[realtime]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325
