// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwgziryzjnwjzzljkzje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3Z3ppcnl6am53anp6bGpremplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNzgwNTIsImV4cCI6MjA2NDY1NDA1Mn0.qEoYtG4HHkUfxuHUWfCr_zt5PCHOom-3RJhFX9iu-64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);